# Generated by Django 4.1.2 on 2022-10-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='service_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
